apiVersion: v1
kind: Service
metadata:
  name: flux-nodejs-app
  namespace: nodejs-app
spec:
  type: LoadBalancer
  selector:
    app: flux-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
